[Icon Theme]
Name=Katu
Comment=Katu OS Icon Theme — Amazônia style
Inherits=breeze-dark,hicolor
Directories=256x256/apps,128x128/apps,64x64/apps,48x48/apps

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[64x64/apps]
Size=64
Context=Applications
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

