[Icon Theme]
Name=Katu
Comment=Katu OS Icon Theme — Amazônia style
Inherits=breeze-dark,hicolor
Directories=256x256/apps,128x128/apps,64x64/apps,48x48/apps,256x256/places,128x128/places,64x64/places,48x48/places,256x256/devices,128x128/devices,64x64/devices,48x48/devices

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[256x256/places]
Size=256
Context=Places
Type=Fixed

[256x256/devices]
Size=256
Context=Devices
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[128x128/devices]
Size=128
Context=Devices
Type=Fixed

[64x64/apps]
Size=64
Context=Applications
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[64x64/devices]
Size=64
Context=Devices
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

