---
# Calamares bootloader module — instala e configura GRUB

efiBootLoaderId:    "katu"
installEFIFallback: false

kernel:       "/vmlinuz"
img:          "/initrd.img"
fallback:     "/initrd.img.bak"

grubInstall:  "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg:      "/boot/grub/grub.cfg"

# Tema GRUB
grubProbe:    "grub-probe"
efiBootMgr:   "efibootmgr"

# Parâmetros do kernel adicionados ao menu GRUB
kernelLine:        " quiet splash"
kernelLineRemove:  [ "noeject", "boot=live", "components", "nomodeset" ]
