# Calamares — módulo displaymanager

displaymanagers:
    - sddm

# Sessão padrão
defaultDesktopEnvironment:
    executable: "startplasma-x11"
    desktopFile: "plasma"

# Configurações SDDM
sddm:
    theme: katu
