---
# Calamares fstab module — gera /etc/fstab no sistema instalado

mountOptions:
    default:    defaults
    btrfs:      defaults,compress=zstd:1,noatime

ssdExtraMountOptions:
    ext4:       discard
    btrfs:      discard=async

efiMountOptions:    "umask=0077"

# Swap via swapfile — preferido vs partição dedicada
mountSwap: true
