# Calamares — módulo keyboard

xkbDataPath: "/usr/share/X11/xkb"

# Padrão brasileiro ABNT2
defaultKeyboardLayout: "br"
defaultKeyboardVariant: ""
defaultKeyboardModel: "abnt2"

# Escrita do arquivo /etc/default/keyboard
keyboardFilePath: "/etc/default/keyboard"
