---
# Calamares unpackfs — copia o squashfs para o disco instalado

unpack:
    -   source: "/run/live/medium/live/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""

exclude:
    - "live"
    - "etc/live"
    - "etc/hostname.live"
