---
# Calamares — módulo users

defaultGroups:
    - name: users
      must_exist: false
    - name: lp
    - name: video
    - name: network
    - name: storage
    - name: wheel
    - name: audio
    - name: sudo
    - name: plugdev
    - name: cdrom
    - name: bluetooth
    - name: netdev

# Não define senha de root — sudo é o padrão Debian
setRootPassword: false

# Autologin disponível — usuário escolhe na tela
doAutologin: true

# Política de senha amigável
passwordRequirements:
    minLength: 6
    maxLength: 128

# Hostname gerado a partir do primeiro nome do usuário
hostname:
    location: HostsFile
    template: "katu-${first}"
    separator:  "-"

# Permitir senha vazia (usuário pode optar por sem senha)
allowWeakPasswords: true
allowWeakPasswordsDefault: false
