# Calamares — módulo users

# Grupos padrão para novo usuário
defaultGroups:
    - name: users
      must_exist: false
    - name: lp
    - name: video
    - name: network
    - name: storage
    - name: wheel
    - name: audio
    - name: sudo
    - name: plugdev
    - name: cdrom
    - name: bluetooth

# Hostname
setRootPassword: false
doAutologin: false

# Política de senha
passwordRequirements:
    minLength: 6

# Hostname padrão
hostname:
    location: HostsFile
    template: "katu-${first}"
    separator: "-"
