---
# Calamares — módulo welcome
# Verificações e mensagens amigáveis em PT-BR

requirements:
    requiredStorage: 20
    requiredRam: 2
    check: [storage, ram, power, root]
    required: [storage, root]

showSupportUrl:     true
showKnownIssuesUrl: false
showReleaseNotesUrl: false

geoip:
    style: "none"
