---
# Katu OS — Calamares settings.conf

modules-search:
  - local

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - hwclock
      - users
      - displaymanager
      - packages
      - shellprocess
      - grubcfg
      - bootloader
      - umount
  - show:
      - finished

branding: katu
prompt-install: true
dont-chroot: false
windowTitle: "Instalador Katu OS"
